# Generated by Django 4.2.4 on 2023-08-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskshadow',
            name='customer_status_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskshadow',
            name='customer_status_type',
            field=models.IntegerField(choices=[(1001, 1001), (1002, 1002), (1003, 1003), (1004, 1004), (1005, 1005), (1006, 1006), (1008, 1008), (1009, 1009), (1010, 1010), (1011, 1011), (1007, 1007), (1105, 1105), (1111, 1111), (1102, 1102), (1104, 1104), (1051, 1051), (1052, 1052), (1053, 1053), (1201, 1201), (1202, 1202), (1203, 1203), (1204, 1204), (1205, 1205), (1206, 1206), (1301, 1301), (1302, 1302), (1303, 1303), (1304, 1304), (1305, 1305), (1306, 1306), (1307, 1307), (1401, 1401), (1402, 1402), (1701, 1701), (2000, 2000), (2002, 2002), (2101, 2101), (2102, 2102), (2200, 2200), (1207, 1207), (1904, 1904), (2300, 2300), (2301, 2301), (1208, 1208), (2400, 2400), (1050, 1050)], default=1001),
        ),
    ]
