# Generated by Django 4.2.4 on 2023-08-29 21:46

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('unscheduled', models.BooleanField(default=False)),
                ('entity_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('template_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskShadow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1001, 1001), (1002, 1002), (1003, 1003), (1004, 1004), (1005, 1005), (1006, 1006), (1008, 1008), (1009, 1009), (1010, 1010), (1011, 1011), (1007, 1007), (1105, 1105), (1111, 1111), (1102, 1102), (1104, 1104), (1050, 1050), (1100, 1100), (1103, 1103), (1051, 1051), (1054, 1054), (1052, 1052), (1106, 1106), (1107, 1107), (1108, 1108), (1109, 1109), (1110, 1110), (1053, 1053), (1201, 1201), (1202, 1202), (1203, 1203), (1204, 1204), (1205, 1205), (1206, 1206), (1301, 1301), (1302, 1302), (1303, 1303), (1304, 1304), (1305, 1305), (1306, 1306), (1307, 1307), (1401, 1401), (1402, 1402), (1501, 1501), (1502, 1502), (1503, 1503), (1504, 1504), (1505, 1505), (1601, 1601), (1602, 1602), (1701, 1701), (1901, 1901), (1902, 1902), (1903, 1903), (1802, 1802), (1801, 1801), (2000, 2000), (2002, 2002), (2101, 2101), (2102, 2102), (2200, 2200), (1207, 1207), (1904, 1904), (2300, 2300), (2301, 2301), (1208, 1208), (2400, 2400), (1506, 1506), (2500, 2500), (2501, 2501)], default=1001)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.IntegerField()),
                ('assigned_group_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_start_delay_time', models.IntegerField(default=15)),
                ('auto_complete_delay_time', models.IntegerField(default=90)),
                ('disable_auto_start_complete', models.BooleanField(default=False)),
                ('statuses', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('mark_enroute_after_complete', models.BooleanField(default=True)),
                ('next_task_info', models.TextField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.user')),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('is_active', models.BooleanField()),
                ('type', models.IntegerField(choices=[(1001, 1001), (1002, 1002), (1003, 1003), (1004, 1004), (1005, 1005), (1006, 1006), (1008, 1008), (1009, 1009), (1010, 1010), (1011, 1011), (1007, 1007), (1105, 1105), (1111, 1111), (1102, 1102), (1104, 1104), (1050, 1050), (1100, 1100), (1103, 1103), (1051, 1051), (1054, 1054), (1052, 1052), (1106, 1106), (1107, 1107), (1108, 1108), (1109, 1109), (1110, 1110), (1053, 1053), (1201, 1201), (1202, 1202), (1203, 1203), (1204, 1204), (1205, 1205), (1206, 1206), (1301, 1301), (1302, 1302), (1303, 1303), (1304, 1304), (1305, 1305), (1306, 1306), (1307, 1307), (1401, 1401), (1402, 1402), (1501, 1501), (1502, 1502), (1503, 1503), (1504, 1504), (1505, 1505), (1601, 1601), (1602, 1602), (1701, 1701), (1901, 1901), (1903, 1903), (1902, 1902), (1801, 1801), (1802, 1802), (2000, 2000), (2002, 2002), (2101, 2101), (2102, 2102), (2200, 2200), (1207, 1207), (1904, 1904), (2300, 2300), (2301, 2301), (1208, 1208), (2400, 2400), (1506, 1506), (2500, 2500), (2501, 2501)], default=1001)),
                ('object_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('task_shadow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.taskshadow')),
            ],
        ),
        migrations.AddField(
            model_name='taskshadow',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.user'),
        ),
        migrations.AddField(
            model_name='taskshadow',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.user'),
        ),
        migrations.AddField(
            model_name='task',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.template'),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('type', models.IntegerField(choices=[(1002, 1002), (1003, 1003), (1004, 1004), (1005, 1005), (1006, 1006), (1008, 1008), (1009, 1009), (1010, 1010), (1105, 1105), (1111, 1111), (1102, 1102), (1104, 1104), (1053, 1053), (1201, 1201), (1202, 1202), (1203, 1203), (1204, 1204), (1205, 1205), (1206, 1206), (1401, 1401), (1402, 1402), (1504, 1504), (1601, 1601), (1602, 1602), (1802, 1802), (1801, 1801), (2000, 2000), (2002, 2002), (2101, 2101), (2102, 2102), (2200, 2200), (1207, 1207), (2300, 2300), (2301, 2301), (1208, 1208), (2400, 2400)])),
                ('permission_group_id', models.IntegerField(choices=[(-1, -1), (1, 1), (2, 2), (3, 3), (9, 9), (8, 8), (7, 7), (4, 4), (5, 5), (6, 6), (51, 51)], default=4)),
                ('status_trigger', models.IntegerField(choices=[(1000, 1000), (1001, 1001), (1002, 1002), ('FORM_SAVE', 'FORM_SAVE'), (1003, 1003), ('STATUS', 'STATUS')], default=1000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.user')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('entity_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_default', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.user')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type', models.IntegerField(choices=[(1001, 1001), (1005, 1005), (1002, 1002), (1003, 1003), (1006, 1006), (1007, 1007), (1004, 1004), (1008, 1008), (1009, 1009), (1010, 1010), (1011, 1011), (1012, 1012), (1013, 1013), (1014, 1014), (1015, 1015), (1016, 1016), (1017, 1017), (1018, 1018), (1019, 1019), (1020, 1020)], default=1007)),
                ('pending_review_reminder_attempts', models.IntegerField(default=2)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.user')),
            ],
        ),
    ]
