# Generated by Django 4.2.4 on 2023-08-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_taskshadow_customer_status_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatusdata',
            name='title',
            field=models.CharField(default='NOTSTARTED', max_length=255),
            preserve_default=False,
        ),
    ]
