# Generated by Django 4.2.4 on 2023-08-30 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_taskstatusdata_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatusdata',
            name='color',
            field=models.CharField(default='#44a7f1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskstatusdata',
            name='reporter_entity_id',
            field=models.ForeignKey(default=496773097, on_delete=django.db.models.deletion.CASCADE, to='application.entity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskstatusdata',
            name='reporter_name',
            field=models.CharField(default='maham', max_length=255),
            preserve_default=False,
        ),
    ]
