# Generated by Django 4.2.4 on 2023-08-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_taskstatusdata_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatusdata',
            name='reporter_entity_id',
            field=models.IntegerField(),
        ),
    ]
