config = {}

config['TASK_AUTO_START_DELAY_TIME_IN_MINUTES'] = 15
config['TASK_AUTO_COMPLETE_DELAY_TIME_IN_MINUTES'] = 90
config['PENDING_REVIEW_REMINDER_ATTEMPTS'] = 2
config['DEFAULT_DAY_TO_START_CALENDER_WEEK_FROM'] = 'SUNDAY'
config['DEFAULT_DAY_TO_END_CALENDER_WEEK_ON'] = 'SATURDAY'
config['ARRIVY_REPORTER_ID'] = 0
config['ARRIVY_REPORTER_NAME'] = 'ARRIVY'

config['PENDING_REVIEW_REMINDER_ATTEMPTS'] = 2